"""
Generate Tasky PWA icons using Pillow — v2 (refined).

Improvements over v1:
  - Background uses a subtle dark blue→deep gradient (was flat black)
  - Clipboard glyph is layered (drop shadow + paper highlight) for depth
  - Tasks are positioned by a tighter golden-ratio rhythm
  - Done task gets a clean accent-blue circle with a crisp tick
  - Active tasks have hollow rings with a faint inner highlight
  - Accent dot moved to bottom-right with a soft halo
  - Maskable variants honour the 80% safe zone strictly
  - Favicon is generated by downsampling the 192-with-bg version so the
    glyph stays sharp at 32px instead of being redrawn

Outputs (same filenames as before):
    icon-192.png            (any-purpose)
    icon-512.png            (any-purpose)
    icon-192-maskable.png   (safe-zone for adaptive icons)
    icon-512-maskable.png   (safe-zone for adaptive icons)
    apple-touch-icon.png    (180x180)
    favicon-32.png          (32x32)

Run from this folder:    python _gen_icons.py
"""

from PIL import Image, ImageDraw, ImageFilter

# ── Brand palette ────────────────────────────────────
BG_TOP    = (26, 35, 50)        # #1a2332  — subtle blue-grey top
BG_BOTTOM = (10, 14, 20)        # #0a0e14  — almost black bottom
PAPER     = (250, 251, 253)
PAPER_DIM = (228, 232, 240)
ACCENT    = (79, 142, 247)      # #4f8ef7  Tasky blue
ACCENT_LO = (52, 105, 207)
LINE_DARK = (130, 145, 165)
LINE_DONE = (165, 175, 195)
SHADOW    = (0, 0, 0, 70)       # drop shadow alpha


def round_rect(draw, xy, radius, fill=None, outline=None, width=0):
    draw.rounded_rectangle(xy, radius=radius, fill=fill, outline=outline, width=width)


# ── Background ───────────────────────────────────────
def make_bg(size, rounded_corners=True):
    """Vertical gradient with optional rounded corners (for non-maskable)."""
    grad = Image.new('RGB', (1, size))
    for y in range(size):
        t = y / (size - 1)
        r = int(BG_TOP[0]    + (BG_BOTTOM[0] - BG_TOP[0])    * t)
        g = int(BG_TOP[1]    + (BG_BOTTOM[1] - BG_TOP[1])    * t)
        b = int(BG_TOP[2]    + (BG_BOTTOM[2] - BG_TOP[2])    * t)
        grad.putpixel((0, y), (r, g, b))
    grad = grad.resize((size, size))

    if rounded_corners:
        # Apply rounded square mask so corners are clipped
        mask = Image.new('L', (size, size), 0)
        m = ImageDraw.Draw(mask)
        m.rounded_rectangle((0, 0, size, size), radius=int(size * 0.22), fill=255)
        rounded = Image.new('RGBA', (size, size), (0, 0, 0, 0))
        rounded.paste(grad, (0, 0), mask)
        return rounded
    else:
        return grad.convert('RGBA')


# ── Clipboard glyph (centred on a transparent canvas) ───
def make_clipboard(size, padding_ratio=0.16):
    """
    Draw the clipboard layered for depth:
      1. Shadow blob below
      2. Paper rectangle (rounded)
      3. Subtle paper highlight
      4. Metal clip on top
      5. Three task rows (hollow rings + lines, last one done w/ tick)
    """
    img = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    pad = int(size * padding_ratio)
    cx, cy = size / 2, size / 2

    board_w = size - pad * 2
    board_h = int(board_w * 1.18)
    board_x0 = int(cx - board_w / 2)
    board_y0 = int(cy - board_h / 2 + size * 0.03)
    board_x1 = board_x0 + board_w
    board_y1 = board_y0 + board_h
    radius = int(board_w * 0.11)

    # ── 1. Drop shadow under board ──
    shadow_layer = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow_layer)
    sd.rounded_rectangle(
        (board_x0 + int(size * 0.012), board_y0 + int(size * 0.025),
         board_x1 + int(size * 0.012), board_y1 + int(size * 0.025)),
        radius=radius, fill=SHADOW
    )
    shadow_layer = shadow_layer.filter(ImageFilter.GaussianBlur(radius=max(2, size // 96)))
    img.alpha_composite(shadow_layer)

    d = ImageDraw.Draw(img)

    # ── 2. Paper board ──
    round_rect(d, (board_x0, board_y0, board_x1, board_y1), radius, fill=PAPER)

    # ── 3. Paper top highlight (subtle white-translucent strip) ──
    hi_layer = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    hd = ImageDraw.Draw(hi_layer)
    hd.rounded_rectangle(
        (board_x0 + int(board_w * 0.04),
         board_y0 + int(board_h * 0.04),
         board_x1 - int(board_w * 0.04),
         board_y0 + int(board_h * 0.18)),
        radius=int(radius * 0.7),
        fill=(255, 255, 255, 60)
    )
    hi_layer = hi_layer.filter(ImageFilter.GaussianBlur(radius=max(1, size // 160)))
    img.alpha_composite(hi_layer)

    # ── 4. Clip on top of the board ──
    clip_w = int(board_w * 0.40)
    clip_h = int(board_h * 0.10)
    clip_x0 = int(cx - clip_w / 2)
    clip_y0 = int(board_y0 - clip_h * 0.55)
    clip_x1 = clip_x0 + clip_w
    clip_y1 = clip_y0 + clip_h
    # tiny shadow under the clip
    clip_shadow = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    cs = ImageDraw.Draw(clip_shadow)
    cs.rounded_rectangle(
        (clip_x0, clip_y0 + int(clip_h * 0.6), clip_x1, clip_y1 + int(clip_h * 0.4)),
        radius=int(clip_h * 0.45), fill=(0, 0, 0, 110)
    )
    clip_shadow = clip_shadow.filter(ImageFilter.GaussianBlur(radius=max(1, size // 200)))
    img.alpha_composite(clip_shadow)
    # clip body — subtle gradient (top brighter)
    for i in range(clip_h):
        t = i / max(1, clip_h - 1)
        c = (
            int(110 - 18 * t),
            int(120 - 18 * t),
            int(135 - 22 * t),
            255
        )
        d.line((clip_x0 + int(clip_h * 0.45), clip_y0 + i,
                clip_x1 - int(clip_h * 0.45), clip_y0 + i), fill=c)
    # rounded ends of the clip
    round_rect(d, (clip_x0, clip_y0, clip_x1, clip_y1), int(clip_h * 0.45), fill=(95, 105, 120))
    # narrow vertical handle in the middle of the clip
    handle_w = int(clip_w * 0.18)
    handle_x0 = int(cx - handle_w / 2)
    handle_y1 = clip_y0 + int(clip_h * 0.55)
    handle_y0 = clip_y0 - int(clip_h * 0.35)
    round_rect(d, (handle_x0, handle_y0, handle_x0 + handle_w, handle_y1),
               int(handle_w * 0.45), fill=(115, 125, 140))

    # ── 5. Three task rows ──
    line_h = max(2, int(board_h * 0.058))
    line_full  = int(board_w * 0.62)
    line_med   = int(board_w * 0.50)
    line_short = int(board_w * 0.42)

    rows = [
        (line_full,  False),
        (line_med,   False),
        (line_short, True),
    ]

    bullet_r  = int(line_h * 0.92)
    bullet_gap = max(2, int(size * 0.018))

    inner_x = board_x0 + int(board_w * 0.22) + bullet_r * 2
    base_y  = board_y0 + int(board_h * 0.34)
    gap     = int(board_h * 0.18)

    for i, (w, done) in enumerate(rows):
        y_mid = base_y + i * gap + line_h // 2
        bx = inner_x - bullet_r * 2 - bullet_gap

        if done:
            # Filled accent circle, with very subtle inner shadow ring
            d.ellipse((bx - bullet_r, y_mid - bullet_r,
                       bx + bullet_r, y_mid + bullet_r), fill=ACCENT)
            # tick mark — calculated points relative to bullet centre
            tick_w = max(2, int(bullet_r * 0.45))
            t1 = (bx - bullet_r * 0.50, y_mid + 0)
            t2 = (bx - bullet_r * 0.05, y_mid + bullet_r * 0.42)
            t3 = (bx + bullet_r * 0.55, y_mid - bullet_r * 0.45)
            d.line([t1, t2], fill=PAPER, width=tick_w)
            d.line([t2, t3], fill=PAPER, width=tick_w)
        else:
            # Hollow ring with stroke, faint inner highlight
            ring_w = max(2, int(bullet_r * 0.30))
            d.ellipse((bx - bullet_r, y_mid - bullet_r,
                       bx + bullet_r, y_mid + bullet_r),
                      outline=LINE_DARK, width=ring_w)

        # Task line (paper-tone bar with rounded ends)
        bar_x0 = inner_x
        bar_x1 = inner_x + w
        bar_y0 = y_mid - line_h // 2
        bar_y1 = y_mid + line_h // 2
        bar_color = LINE_DONE if done else PAPER_DIM
        round_rect(d, (bar_x0, bar_y0, bar_x1, bar_y1),
                   max(1, line_h // 2), fill=bar_color)

        if done:
            # Strike-through (accent-tinted, slightly thinner than the bar)
            strike_w = max(2, int(line_h * 0.34))
            d.line((bar_x0 + line_h // 4, y_mid,
                    bar_x1 - line_h // 4, y_mid),
                   fill=ACCENT_LO, width=strike_w)

    return img


# ── Optional accent dot in bottom-right (with soft halo) ───
def add_accent_dot(base):
    size = base.size[0]
    halo = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    hd = ImageDraw.Draw(halo)
    r_dot  = int(size * 0.06)
    r_halo = int(r_dot * 2.4)
    cx = size - int(size * 0.18)
    cy = size - int(size * 0.18)
    # Halo (large, low-alpha, blurred)
    hd.ellipse((cx - r_halo, cy - r_halo, cx + r_halo, cy + r_halo),
               fill=ACCENT + (90,))
    halo = halo.filter(ImageFilter.GaussianBlur(radius=max(2, size // 64)))
    base.alpha_composite(halo)
    # Dot
    d = ImageDraw.Draw(base)
    d.ellipse((cx - r_dot, cy - r_dot, cx + r_dot, cy + r_dot), fill=ACCENT)
    # tiny highlight
    r_hl = int(r_dot * 0.3)
    d.ellipse((cx - r_dot * 0.4 - r_hl, cy - r_dot * 0.4 - r_hl,
               cx - r_dot * 0.4 + r_hl, cy - r_dot * 0.4 + r_hl),
              fill=(255, 255, 255, 200))
    return base


def generate_icon(size, maskable=False, with_accent_dot=True):
    if maskable:
        # Strict 80% safe zone, no rounded corners (Android masks them)
        bg = make_bg(size, rounded_corners=False)
        glyph = make_clipboard(size, padding_ratio=0.24)
        bg.alpha_composite(glyph)
        # No accent dot on maskable — could be clipped by some adaptive masks
        return bg
    else:
        bg = make_bg(size, rounded_corners=True)
        glyph = make_clipboard(size, padding_ratio=0.16)
        bg.alpha_composite(glyph)
        if with_accent_dot:
            bg = add_accent_dot(bg)
        return bg


def make_favicon():
    """Render a 192-sized variant then downsample for crispness at 32px."""
    big = generate_icon(192)
    return big.resize((32, 32), Image.LANCZOS)


def save(img, path):
    img.save(path, 'PNG', optimize=True)
    print(f'  wrote {path}  ({img.size[0]}x{img.size[1]}, {img.tobytes().__sizeof__()} bytes raw)')


if __name__ == '__main__':
    print('Generating Tasky icons (v2 refined)…')
    save(generate_icon(192),                 'icon-192.png')
    save(generate_icon(512),                 'icon-512.png')
    save(generate_icon(192, maskable=True),  'icon-192-maskable.png')
    save(generate_icon(512, maskable=True),  'icon-512-maskable.png')
    save(generate_icon(180),                 'apple-touch-icon.png')
    save(make_favicon(),                     'favicon-32.png')
    print('done.')
